### ISSUE TITLE
(見本)ログインページを作ろう

### ISSUE THREAD

**Issue by technicakidz** [annakama1213/Djangogirls#1]
### 概要
(何を実現すればよい/したいか記載する)
アプリにログイン機能を追加したい．

### 完了の定義
(ここに書かれていることを満たせていれば issue を完了できる)
- `example/path_file/login.py`  が作成されている
- 実際にログイン画面が起動してテストのユーザ名/IDでログインできる

### TODO
(ここは具体的なタスクを記載)
- [x] URL に `/login` パスが追加されている
- [x] テスト用のDBが追加されている

**Comment by technicakidz** [comment]
見本の issue をたててみました．記載するにあたりマークダウンの記法や内容の参考にしてください．

**Comment by annakama1213** [comment]
**Django ORM**
