### ISSUE TITLE
テンプレート内の動的データ

### ISSUE THREAD

**Issue by annakama1213** [annakama1213/Djangogirls#3]
**テンプレート内の動的データ**

## 目的(概要)
ポストの内容を表示する

## 完了定義
以下に記述する実装を完了したら issue は close ．

## 操作概要
Post Model=models.pyへ定義
Post list+テンプレート=views.py
HTMLファイルへ出力するために、ビューへ
- [x] Post listビューから表示したいモデルデータを取り出し
- [x] どのテンプレートファイルに兵頭させるか、を記述する。

▼具体的なやり方
エディタで実施
- [x] blog/views.py
```
from django.shortcuts import render
from .models import Post
```
### models.pyのモデルをインクルードする
```
def post_list(request):
    return render(request, 'blog/post_list.html', {})
```
- [ ]  blog/views.py
```
from django.shortcuts import render
from django.utils import timezone
from .models import Post

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
```

### 公開したブログ記事を published_順に表示する
```
    return render(request, 'blog/post_list.html', {'posts': posts})
```
`{}` の中に引数を記述する時は、名前と値をセットで、表示させたいのはクエリセットのデータなので `posts` を指定。前の方の posts : シングルクォート で囲まれて、 `'posts'` は名前、後ろの方の `posts` は値、クエリセットのことです。

**Comment by annakama1213** [comment]
▼ポストの内容を表示する
Post Model=models.pyへ定義
Post list+テンプレート=views.py
→HTMLファイルへ出力するために、
ビューへ
- [ ] Post listビューから表示したいモデルデータを取り出し
- [ ] どのテンプレートファイルに兵頭させるか、を記述する。

▼具体的なやり方
エディタで実施
- [ ] ①blog/views.py
from django.shortcuts import render
from .models import Post
#models.pyのモデルをインクルードする

def post_list(request):
    return render(request, 'blog/post_list.html', {})

- [ ]② blog/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Post

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
#公開したブログ記事を published_順に表示する
    return render(request, 'blog/post_list.html', {'posts': posts})
#{} の中に引数を記述する時は、名前と値をセットで、表示させたいのはクエリセットのデータなので posts を指定。前の方の posts : シングルクォート で囲まれて、 'posts' は名前、後ろの方の posts は値、クエリセットのことです。

**Comment by technicakidz** [comment]
master branch に直接 push した(本当はこの章のブランチを作成してPRのつもりでした)が，ご自身のローカルサーバを起動して画面プレビューが確認できたので完了！
チェックボックスを埋めて issue は close でOKです．
