### ISSUE TITLE
Django テンプレート

### ISSUE THREAD

**Issue by annakama1213** [annakama1213/Djangogirls#4]

**Comment by annakama1213** [comment]
吉田先生へ確認

▼テンプレートタグ
Djangoテンプレートタグ 
→HTMLにPyhtonのようなコードを埋め込むことができて、動的なウェブサイトが作れる

▼ここの表示がうまくいかない
https://tutorial.djangogirls.org/ja/django_templates/
ブログ一覧テンプレートの表示
前の章で、posts 変数でテンプレートに記事のリストを渡しました。今からHTMLで表示をしてみましょう。

Djangoテンプレートで変数を表示するためには、次のように変数の名前を二重中括弧で括ります。

blog/templates/blog/post_list.html
{{ posts }}
これを blog/templates/blog/post_list.html テンプレートでやってみましょう。 エディタでこのファイルを開き、2つめの <div> から3つめの </div> までをまるごと {{ posts }} に置き換えて下さい。 ファイルを保存してページをリロードすると：

図 13.1

見たとおり、このようになります。

**Comment by technicakidz** [comment]
メモ：仮想サーバ(pythonanywhere)で更新できるか確認する．

**Comment by annakama1213** [comment]
## 解決策
- [x] ローカルサーバーでの挙動を確認する。 http://127.0.0.1:8000/　
- [x] 上記ができている場合は、デプロイができていない可能性が高いので、再度GithubへのPushとPythonanywhereへのBash上でのPullを行う。
