### ISSUE TITLE
Django フォーム

### ISSUE THREAD

**Issue by annakama1213** [annakama1213/Djangogirls#5]

**Comment by technicakidz** [comment]
メモ：次回(1/16)までに実装を進める．
チェックポイント
- [x]  branch がきられている
- [x] PR が紐ついている
- [x] ローカルサーバで挙動の確認ができている
- [x] デプロイされている

**Comment by annakama1213** [comment]
**問題**
下記対応をしたがPythonanywhere上で下記エラーが出る。

**実際のエラー抜粋**
#post_listの属性が定義されていない
AttributeError at /
module 'blog.views' has no attribute 'post_list'

>>>Request Method:GET
>>>Request URL:http://annakama1213.pythonanywhere.com/
>>>Django Version:2.2.25
>>>Exception Type:AttributeError
>>>Exception Value:module 'blog.views' has no attribute 'post_list'
>>>Exception Location:/home/annakama1213/annakama1213.pythonanywhere.com/blog/urls.py in >>><module>, line 5
>>>Python Executable:/usr/local/bin/uwsgi
>>>Python Version:3.6.13
>>>Python Path:['/home/annakama1213/annakama1213.pythonanywhere.com',
 >>>'/var/www',
 >>>'.',
 >>>'',
 >>>'/var/www',
 >>>'/usr/local/lib/python36.zip',
 >>>'/usr/local/lib/python3.6',
 >>>'/usr/local/lib/python3.6/lib-dynload',
 >>>'/home/annakama1213/.virtualenvs/annakama1213.pythonanywhere.com/lib/python3.6/site-packages']
>>>Server time:日, 16 1月 2022 11:40:54 +0900

- [x] #post_listの記載があるところはblog/urls.pyを確認

>>>from django.urls import path 
>>>from . import views

>>>urlpatterns = [
   >>> path('', views.post_list, name='post_list'),
#これは 'http://127.0.0.1:8000/' というアドレスにアクセスしてきたら views.post_list が正しい行き先だということをDjangoに伝えています。
    >>>path('post/<int:pk>/', views.post_detail, name='post_detail'),
    >>>path('post/new/', views.post_new, name='post_new'),
    >>>path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
>>>]

**Comment by annakama1213** [comment]
**続き**

views.pyを下記に変更したところ、他のエラーとなった。

>>>from django.shortcuts import render, get_object_or_404
>>>from django.utils import timezone
>>>from .models import Post
>>>from .forms import PostForm
>>>from django.shortcuts import redirect

>>>def post_list(request):
   >>> posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
   >>> return render(request, 'blog/post_list.html', {'posts': posts})

>>>def post_edit(request, pk):
    >>>post = get_object_or_404(Post, pk=pk)
   >>> if request.method == "POST":
       >>> form = PostForm(request.POST, instance=post)
       >>> if form.is_valid():
           >>> post = form.save(commit=False)
            >>>post.author = request.user
            >>>post.published_date = timezone.now()
            >>>post.save()
           >>> return redirect('post_detail', pk=post.pk)
    >>>else:
        >>>form = PostForm(instance=post)
    >>>return render(request, 'blog/post_edit.html', {'form': form})

#post_detailの属性が定義されていない
AttributeError at /
module 'blog.views' has no attribute 'post_detail'

**Comment by annakama1213** [comment]
問題
[デプロイされている]について

下記エラーが出ている

# pythonanywhere上のアクセスログで出ている

```

60.138.56.22 - - [16/Jan/2022:10:11:28 +0000] "POST /post/new/ HTTP/1.1" 500 65876 "http://annakama1213.pythonanywhere.com/post/new/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36" "60.138.56.22" response-time=0.060

```

## エラーログは下記

```
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f0f535dcc88>>": "Post.author" must be a "User" instance.

```

- [x] 新規投稿が成功する

**Comment by annakama1213** [comment]
## 解決策
- [x] https://annakama1213.pythonanywhere.com/admin/ へログインする
- [x] 上記にログインした上で再度、https://annakama1213.pythonanywhere.com/ へポストをし保存をする
- [x] 確認として、再度adminで保存できているかも確認する
※https://annakama1213.pythonanywhere.com/ へのログインが保持されているため実行できるが、ログインのセッションが切れると再度エラーになるので注意する。
